// app.js

// ==== SCROLL LOGIC ====
window.addEventListener('scroll', () => {
  const navbar = document.getElementById('navbar');
  if (window.scrollY > 50) {
    navbar.classList.add('scrolled');
  } else {
    navbar.classList.remove('scrolled');
  }
});

function scrollToModules() {
  document.getElementById('modules').scrollIntoView({ behavior: 'smooth' });
}

// ==== HAMBURGER MENU ====
const hamburger = document.getElementById('hamburger');
const navLinks = document.querySelector('.nav-links');
if(hamburger) {
  hamburger.addEventListener('click', () => {
    navLinks.classList.toggle('open');
  });
}

// ==== MODAL LOGIC ====
function openModule(type) {
  if (type === 'fresher') {
    document.getElementById('fresherModal').classList.add('active');
    resetForm('fresher');
  } else if (type === 'experienced') {
    document.getElementById('expModal').classList.add('active');
    resetForm('exp');
  }
}

function closeModal(modalId) {
  document.getElementById(modalId).classList.remove('active');
}

// ==== MULTISTEP FORM LOGIC ====
let fStep = 1;
const fMaxSteps = 5;

let eStep = 1;
const eMaxSteps = 5;

function updateProgress(type, step, maxSteps) {
  const progressFill = document.getElementById(`${type}Progress`);
  const progressLabel = document.getElementById(`${type}ProgressLabel`);
  if (!progressFill || !progressLabel) return;
  const percent = (step / maxSteps) * 100;
  progressFill.style.width = `${percent}%`;
  progressLabel.textContent = `Step ${step} of ${maxSteps}`;
}

function resetForm(type) {
  if (type === 'fresher') {
    fStep = 1;
    showStep('fresher', fStep);
  } else {
    eStep = 1;
    showStep('exp', eStep);
  }
}

function showStep(type, step) {
  const maxSteps = type === 'fresher' ? fMaxSteps : eMaxSteps;
  const prefix = type === 'fresher' ? 'f' : 'e';
  
  // Hide all steps
  for (let i = 1; i <= maxSteps; i++) {
    const el = document.getElementById(`${prefix}Step${i}`);
    if (el) {
      el.classList.remove('active');
    }
  }
  
  // Show target
  const targetEl = document.getElementById(`${prefix}Step${step}`);
  if (targetEl) {
    targetEl.classList.add('active');
  }
  
  // Update UI
  updateProgress(type, step, maxSteps);
  updateButtons(type, step, maxSteps);
}

function updateButtons(type, step, maxSteps) {
  const backBtn = document.getElementById(`${type}Back`);
  const nextBtn = document.getElementById(`${type}Next`);
  const generateBtn = document.getElementById(`${type}Generate`);
  if(!backBtn || !nextBtn || !generateBtn) return;
  
  if (step === 1) {
    backBtn.style.display = 'none';
  } else {
    backBtn.style.display = 'block';
  }
  
  if (step === maxSteps) {
    nextBtn.style.display = 'none';
    generateBtn.style.display = 'block';
  } else {
    nextBtn.style.display = 'block';
    generateBtn.style.display = 'none';
  }
}

function nextStep(type) {
  if (type === 'fresher') {
    if (fStep < fMaxSteps) {
      fStep++;
      showStep('fresher', fStep);
    }
  } else if (type === 'exp') {
    if (eStep < eMaxSteps) {
      eStep++;
      showStep('exp', eStep);
    }
  }
}

function prevStep(type) {
  if (type === 'fresher') {
    if (fStep > 1) {
      fStep--;
      showStep('fresher', fStep);
    }
  } else if (type === 'exp') {
    if (eStep > 1) {
      eStep--;
      showStep('exp', eStep);
    }
  }
}

// ==== AI GENERATOR MOCKS ====
function generateObjective() {
  const btn = document.getElementById('generateObjectiveBtn');
  const textarea = document.getElementById('f_objective');
  const roleInput = document.getElementById('f_target_role');
  const roleName = roleInput && roleInput.value ? roleInput.value : '[Your Target Role]';
  
  if(!btn || !textarea) return;
  
  // Loading state
  btn.innerHTML = '<span>⏳ Generating...</span>';
  btn.style.opacity = '0.7';
  
  setTimeout(() => {
    textarea.value = `Enthusiastic and adaptable professional with a strong foundation in modern web technologies. Seeking a challenging role as a ${roleName} to leverage my technical skills, contribute to real-world projects, and continuously learn in a dynamic environment.`;
    btn.innerHTML = '<span>✨ Generated by AI</span>';
    btn.style.opacity = '1';
    btn.style.background = 'rgba(16,185,129,0.2)';
    btn.style.borderColor = 'rgba(16,185,129,0.5)';
    btn.style.color = '#34d399';
  }, 400); // 400ms for fast experience
}

function generateSummary() {
  const btn = document.querySelector('.exp-ai-btn');
  const textarea = document.getElementById('e_summary');
  const roleInput = document.getElementById('e_target_role');
  const title = roleInput && roleInput.value ? roleInput.value : 'Senior Professional';
  
  if(!btn || !textarea) return;

  btn.innerHTML = '<span>⏳ Generating...</span>';
  btn.style.opacity = '0.7';
  
  setTimeout(() => {
    textarea.value = `Results-driven ${title} with proven expertise in leading cross-functional teams and optimizing business processes. Adept at identifying technical solutions to complex challenges and driving efficiency improvements that reduce costs and increase revenue. Strong track record of mentoring junior staff and delivering projects on time and under budget.`;
    btn.innerHTML = '<span>✨ Generated by AI</span>';
    btn.style.opacity = '1';
    btn.style.background = 'rgba(16,185,129,0.2)';
    btn.style.borderColor = 'rgba(16,185,129,0.5)';
    btn.style.color = '#34d399';
  }, 400); // 400ms for fast experience
}

// ==== TEMPLATE SELECTION ====
function selectTemplate(element, type) {
  // Find parent container
  const container = element.closest('.template-selector');
  if(!container) return;
  // Remove active from all siblings
  container.querySelectorAll('.tmpl-option').forEach(el => el.classList.remove('active'));
  // Add active to clicked
  element.classList.add('active');
}

function switchTab(type) {
  // Tabs
  const tabFresher = document.getElementById('tab-fresher');
  const tabExp = document.getElementById('tab-exp');
  
  if(tabFresher && tabExp) {
    tabFresher.classList.remove('active');
    tabExp.classList.remove('active');
    document.getElementById(`tab-${type}`).classList.add('active');
  }
  
  // Grids
  const fresherGrid = document.getElementById('fresherTemplates');
  const expGrid = document.getElementById('expTemplates');
  
  if(fresherGrid && expGrid) {
    if (type === 'fresher') {
      fresherGrid.classList.remove('hidden');
      expGrid.classList.add('hidden');
    } else {
      expGrid.classList.remove('hidden');
      fresherGrid.classList.add('hidden');
    }
  }
}

// ==== GENERATE & SUCCESS LOGIC ====
function generateResume(type) {
  // Close builder modal
  if(type === 'fresher') closeModal('fresherModal');
  if(type === 'exp') closeModal('expModal');
  
  // Open success modal
  const successModal = document.getElementById('successModal');
  if(successModal) {
    successModal.classList.add('active');
  }
}

function openLoginModal() {
  const modal = document.getElementById('loginModal');
  if(modal) modal.classList.add('active');
}

function closeLoginModal() {
  const modal = document.getElementById('loginModal');
  if(modal) modal.classList.remove('active');
}

// ==== DOWNLOAD LOGIC ====
function downloadResume(format) {
  const btn = document.querySelector(`.btn-download.${format}`);
  if(!btn) return;
  const originalText = btn.innerHTML;
  
  btn.innerHTML = '<span>🔄 Downloading...</span>';
  btn.style.opacity = '0.8';
  
  setTimeout(() => {
    btn.innerHTML = '<span>✅ Download Complete</span>';
    setTimeout(() => {
      btn.innerHTML = originalText;
      btn.style.opacity = '1';
    }, 2000);
  }, 800);
}
